# Generated by Django 6.0.7 on 2026-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('No_of_Guests', models.IntegerField()),
                ('BookingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventory', models.IntegerField(default=0)),
            ],
        ),
        # Rename fields in MenuItem from lowercase to uppercase
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='inventory',
            new_name='Inventory',
        ),
    ]


