# Generated by Django 6.0.7 on 2026-08-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_booking_menu_remove_menuitem_id_and_more'),
    ]

    operations = [
        # 0002 already brought MenuItem in line with the current model.
    ]
