# Generated by Django 6.0.7 on 2026-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_remove_menuitem_id_alter_menuitem_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='Inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
